### PR TITLE
setup helpers

### PR DESCRIPTION
**Pull request by bpoldrack**
Simplest version ATM works fine given that authentication is set up (still env vars).
A project "totally_new" is created on OSF, special-remote initialized and functioning:

```
$ datalad create-sibling-osf totally_new osf
$ git annex copy --to osf .
copy file1 (to osf...) 
ok
copy file2 (to osf...) 
ok
(recording state in git...)
```
This needs some more things to cover (particularly in light of #30) and tests, of course, which requires #20 to come to an conclusion.

I'll keep going ...

### CODE REVIEW

**Comment by bpoldrack** [comment]
Apart from the failing doc builds, this is ready.

Provides a (very) basic datalad command `create-sibling-osf` to be executed on an existing local datalad dataset. (an annex repository)
It takes a project title and a name for the to-be configured OSF special remote and creates that project on OSF (given credentials) and initializes the special remote accordingly.
After `datalad create-sibling-osf <project title> <remote name>`, a subsequent `git annex copy . --to <remote name>` would copy all the data to OSF.

Ping @DorienHuijser

**Comment by bpoldrack** [comment]
There are further TODOs, of course, but this enables the basic functionality and can be documented.
I'd then keep working in a separate PR.

**Comment by mjboos** [comment]
Cool! Can we also pass exporttree=yes to create-sibling-osf?

**Comment by bpoldrack** [comment]
Thx, @adswa !

@mjboos : Not yet.

**Comment by mjboos** [comment]
When calling `datalad create-sibling-osf osftest osftest` (in a correctly initialized datalad project) I get

> [ERROR  ] 'path' [utils.py:default_result_renderer:501] (KeyError)

**Comment by bpoldrack** [comment]
@mjboos : Ahh - the joys of unittesting vs. real use ;-)
Will fix. Thanks much!

**Comment by mjboos** [comment]
Sure :)
@bpoldrack will you include the exporttree functionality today?
On this depends how we would structure the examples

**Comment by bpoldrack** [comment]
@mjboos :

1. Bug should be fixed. Command is now supposed to look like this:
```
❱ datalad create-sibling-osf result osf-store
create-project-osf(ok): https://osf.io/52bd7/
add-sibling-osf(ok)
```

2.: export functionality: Not sure. I'll try, although depends on @mih  finishing the functional part.

**Pull request merged**
