### PR TITLE
ENH: use nose-exclude (for osfclient tests) and provide [devel]

### PR DESCRIPTION
**Pull request by yarikoptic**
I am not really seeing utility of test_requires. According to
https://setuptools.readthedocs.io/en/latest/setuptools.html

    If your project’s tests need one or more additional packages besides
    those needed to install it, you can use this option to specify
    them. It should be a string or list of strings specifying what other
    distributions need to be present for the package’s tests to run. When
    you run the test command, setuptools will attempt to obtain
    these (even going so far as to download them using EasyInstall). Note
    that these required projects will not be installed on the system where
    the tests are run, but only downloaded to the project’s setup
    directory if they’re not already installed locally.

    New in 41.5.0: Deprecated the test command.

so either I am reading it wrong or test_requires isn't really
useful/used in any of our typical development scenarios (I could be wrong).

Thus also adding [devel] extras requires target which is typically
used by all other datalad products/extension.  Closes gh-121

### CODE REVIEW

**Comment by yarikoptic** [comment]
windows failure 
```
  File "C:\hostedtoolcache\windows\Python\3.8.3\x64\lib\site-packages\datalad_osf\create_sibling_osf.py", line 317, in custom_result_renderer
    default_result_renderer(res)
  File "C:\hostedtoolcache\windows\Python\3.8.3\x64\lib\site-packages\datalad\interface\utils.py", line 506, in default_result_renderer
    path=relpath(path, res['refds']) if path and res.get('refds') else path,
  File "C:\hostedtoolcache\windows\Python\3.8.3\x64\lib\ntpath.py", line 703, in relpath
    raise ValueError("path is on mount %r, start on mount %r" % (
ValueError: path is on mount 'D:', start on mount 'C:'
```
suggests to blame fresh datalad 0.13.1 ... may be the TEMPDIR fixup?

**Comment by adswa** [comment]
Re-triggered the test with 0.13.2, we now get plenty of

```
=====================================================================

ERROR: Failure: ModuleNotFoundError (No module named 'osfclient')

----------------------------------------------------------------------
```
@yarikoptic

**Comment by adswa** [comment]
FTR: Given that the osfclient has seen a bit of maintenance and a 0.0.4 release recently, I tried to see whether we can rip out the custom osfclient subtree (from mih's fork) and just add it osfclient as a dependency (which would spare us to exclude osfclient tests) - sadly, that doesn't work. osfclient 0.0.4 seems to still lack token authentication

**Comment by yarikoptic** [comment]
I guess the relevant PR is https://github.com/osfclient/osfclient/pull/163#issuecomment-696889834 ?

If you do not intend to run osfclient tests in your copy, you could just need to add `raise SkipTest("do not run osfclient tests in our copy, we believe it works")` to `__init__.py` of its `tests/` or smth like that

**Comment by felliott** [comment]
I've pushed an update to `osfclient`'s `develop` branch that includes support for Personal Access Tokens.  PLMK if it works for you!

**Comment by mih** [comment]
FTR: #136 is the prelude to dropping the osfclient fork entirely, and making most of the PR obsolete.

**Comment by adswa** [comment]
I have removed nose-exclude-related changes, but kept the devel target. as soon as the osfclient is a dependency, not a subtree anymore, this should be good to go, I think.

**Comment by mih** [comment]
This behavior should now be achieved in `master`, in part by cherry-picking from this PR. Please complain, if things went wrong.

**Pull request closed without merging**
