### PR TITLE
Initialize git annex special remote with chunking to circumvent file size limits

### LINKED ISSUE #116: Make git-annex special remote config aware of 5GB filesize limit
There is little we can do about that for "exports", but when used as a regular annex, we can enable chunking and set an appropriate file size limit. This way it would be possible to store files of arbitrary size and have git-annex (re)assemble them.

### PR DESCRIPTION
**Pull request by adswa**
This wants to fix #116 by initializing the special remote with a default chunk size of 50MB. ``initremote``'s ``chunk`` parameter is exposed via a ``--chunk`` argument to allow configuring the chunk size or disable chunking at the time of sibling creation.

Locally, I was able to push a >5GB file to the OSF with this change.

I'm unsure on how to approach unit tests, though - are there related tests in ``datalad`` that test chunk sizes/chunking?

### CODE REVIEW

**Comment by yarikoptic** [comment]
Why just 50mb if like 5gb? Why not eg 1gb? I have never tested the effect from chunking on transfer etc performance but I assume there should be some

**Comment by adswa** [comment]
I agree that we should test this on different infrastructure. Here's what the [docs](https://git-annex.branchable.com/chunking/) say:

> Good chunk sizes will depend on the remote, but a good starting place is probably 1MiB. Very large chunks are problematic, both because git-annex needs to buffer one chunk in memory when uploading, and because a larger chunk will make resuming interrupted transfers less efficient. On the other hand, when a file is split into a great many chunks, there can be increased overhead of making many requests to the remote.

**Comment by adswa** [comment]
With very large datasets and chunking, rate limiting (#28) may also be a point to consider.

**Comment by yarikoptic** [comment]
Thank you! So it feels that the best course of action is not too have chunking enabled by default but error out and instruct user to enable chunking when any file to be uploaded is bigger than 5gb... I don't know if chunking could be enabled on existing remote and what effect it would have.

**Comment by adswa** [comment]
> I don't know if chunking could be enabled on existing remote and what effect it would have.

Yeah, that was what I was thinking about when implementing this, too. I would be fine with making the default ``0`` to disable chunking - changing to a chunking size could be done afterwards with ``enableremote``, if I am not mistaken.

> but error out and instruct user to enable chunking when any file to be uploaded is bigger than 5gb

that raises a good point, the current error when uploading too large files is maximally uninformative at the moment:

```
datalad push --to osf-nochunk                                           127 !
Push to 'osf-nochunk':  25%|███         | 1.00/4.00 [00:00<00:00, 6.49k Steps/s
[ERROR  ] Could not create a new file at (MD5E-s5500000000--d7251c8712f1810b3fe77f571f1c4a91) nor update it.                                                     
| This could have failed because --fast is enabled. 
[copy(/home/adina/scratch/mytest2/areallylargefile)] 
copy(error): areallylargefile (file) [Could not create a new file at (MD5E-s5500000000--d7251c8712f1810b3fe77f571f1c4a91) nor update it.                        
This could have failed because --fast is enabled.]

```

**Comment by yarikoptic** [comment]
FWIW
> that raises a good point, the current error when uploading too large files is maximally uninformative at the moment:

I wonder if OSF returns any more informative information in the response headers (something like , so may be even hardcoding 5GB size in the code would not be necessary... but looking at https://developer.osf.io/#tag/Errors-and-Error-Codes I see nothing relevant :-/ needs to be tried ;-)

**Comment by mih** [comment]
Chunking below the effective limit can be useful (git-annex can download chunks in parallel IIRC), but it increases API usage (more requests, reaching the daily limit faster), and the substantial request latency (more than a second, even on fast(ish) connections) quickly eats up any benefits when the chunk size is too small.

I'd say, and agree, that things should be tried and benchmarked. Let's release 0.2.0 without this feature and target the next one.

**Comment by adswa** [comment]
>  Let's release 0.2.0 without this feature and target the next one.

agreed.

**Comment by adswa** [comment]
With regard to more informative error messages...

> I wonder if OSF returns any more informative information in the response headers (something like , so may be even hardcoding 5GB size in the code would not be necessary... but looking at https://developer.osf.io/#tag/Errors-and-Error-Codes I see nothing relevant :-/ needs to be tried ;-)

I couldn't find anything informative, but both my git-annex special remote debugging as well as HTTP request foo is weak ;-)

The obscure error message is raised by OSF client code (which doesn't check for too large files at all):

https://github.com/datalad/datalad-osf/blob/4218aaa13c52e5dfed5dad729dceea5a9f20dde5/datalad_osf/osfclient/osfclient/models/storage.py#L130-L132

For better errors, would it make sense and is it possible to do something like ``git annex examinekey <key> --format='${bytesize}\n'`` in the special remote code on local files after an unsuccessful transfer if chunking is disabled? I.e., something like a hook?

**Comment by adswa** [comment]
I have benchmarked a tiny bit using the following script:

```
#!/usr/bin/bash

set -eu
set -x

cd "$(mktemp -d ${TMPDIR:-/tmp}/dl-XXXXXXX)"
datalad create .
head -c 1G </dev/urandom >myfile1G
head -c 500MB </dev/urandom >myfile500MB
head -c 100MB </dev/urandom >myfile100MB
datalad save .
for chunk in 50mb 100mb 150mb 200mb 250mb;
   do datalad create-sibling-osf --mode annex --chunk $chunk -s osf_{$chunk};
      time datalad push --to osf_{$chunk};
done
```

no chunking:
```
real    2m50.040s                                                                                                   
user    0m5.82s
sys     0m4.29s
```
50mb:
```
real    4m27.573s
user    0m6.370s
sys     0m4.543s
```
100mb:
```
real    2m39.946s
user    0m5.883s                  
sys     0m4.383s  
```
150mb:
```
real    2m53.841s                                                                                                  
user    0m5.867s
sys     0m4.588s
```

200mb:
```
real    2m35.089s                                                                                                  
user    0m6.032s
sys     0m5.159s
```
250mb:
```
real    2m0.806s                                                                                                   
user    0m5.599s
sys     0m4.699s
```

improvements on how to benchmark this are very welcomed :)

**Comment by adswa** [comment]
Given the 5GB space limit on OSF, this feature isn't really that required anymore, right? Shall we close this?

**Pull request closed without merging**
