### PR TITLE
Update clone command in description via PATCH request with actual project ID

### PR DESCRIPTION
**Pull request by adswa**
This is in response to @yarikoptic in #125:

> although description says it that it is just "an example", IMHO would be better to tune it to use this particular dataset id (n6bgd) not some other q8xnk, so fast/silly readers like me do not just skip the preamble of the lengthy description and would start assuming that may be the ID is for the same dataset but some different version or smth

With the changes in this PR, the example is succeeded by a "This particular project can be cloned using 'datalad clone osf://actual-id'". An example project is [here](https://osf.io/24z35/).

If desired, the patch method can be used to implement an updating mechanism for projects from the command line (e.g., update tags, category, project description, private/public, ...)

TODO:
- [ ] tests

### CODE REVIEW

**Comment by adswa** [comment]
For some reason, the windows tests timed out. I will restart them

**Comment by adswa** [comment]
The Windows tests keep timing out. They manage to do 2 tests, and then hang in ``test_create_osf_export``.

Here is a summary from the ``run tests`` section of the workflow logs:

```

    Directory: D:\a\datalad-osf\datalad-osf

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           8/17/2020  2:31 PM                __testhome__
# WTF
## configuration <SENSITIVE, report disabled by configuration>
## datalad 
  - full_version: 0.13.2
  - version: 0.13.2
## dataset 
  - id: None
  - metadata: <SENSITIVE, report disabled by configuration>
  - path: D:\a\datalad-osf\datalad-osf
  - repo: GitRepo
## dependencies 
  - annexremote: 1.4.3
  - appdirs: 1.4.4
  - boto: 2.49.0
  - cmd:7z: 19.00
  - cmd:annex: 8.20200720.2-g8bfa7990b
  - cmd:bundled-git: UNKNOWN
  - cmd:git: 2.28.0.windows.1
  - cmd:system-git: 2.28.0.windows.1
  - cmd:system-ssh: for
  - humanize: 2.6.0
  - iso8601: 0.1.12
  - keyring: 21.3.0
  - keyrings.alt: 3.4.0
  - msgpack: 1.0.0
  - requests: 2.24.0
  - tqdm: 4.48.2
  - wrapt: 1.12.1
## environment 
  - PATH: C:\Program Files\PowerShell\7;C:\Users\runneradmin\AppData\Roaming\Python\Python38\Scripts;C:\hostedtoolcache\windows\Python\3.8.5\x64\Scripts;C:\hostedtoolcache\windows\Python\3.8.5\x64;C:\Program Files\Mercurial\;C:\Program Files\MongoDB\Server\4.2\bin;C:\ProgramData\kind;C:\vcpkg;C:\cf-cli;C:\Program Files (x86)\NSIS\;C:\Program Files\Mercurial\;C:\hostedtoolcache\windows\stack\2.3.1\x64;C:\ProgramData\chocolatey\lib\ghc.8.10.1\tools\ghc-8.10.1\bin;C:\Program Files\dotnet;C:\mysql-5.7.21-winx64\bin;C:\Program Files\R\R-4.0.2\bin\x64;C:\Program Files\Java\jdk8u265-b01\bin;C:\SeleniumWebDrivers\GeckoDriver;C:\Program Files (x86)\sbt\bin;C:\Rust\.cargo\bin;C:\Program Files (x86)\GitHub CLI;C:\Program Files\Git\bin;C:\hostedtoolcache\windows\go\1.14.6\x64\bin;C:\hostedtoolcache\windows\Python\3.7.8\x64\Scripts;C:\hostedtoolcache\windows\Python\3.7.8\x64;C:\hostedtoolcache\windows\Ruby\2.5.8\x64\bin;C:\npm\prefix;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\ProgramData\Chocolatey\bin;C:\Program Files\Docker;C:\Program Files\PowerShell\7\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager;C:\Program Files\nodejs\;C:\Program Files\OpenSSL\bin;C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;c:\tools\php;C:\Program Files (x86)\sbt\bin;C:\Program Files (x86)\Subversion\bin;C:\SeleniumWebDrivers\ChromeDriver\;C:\SeleniumWebDrivers\EdgeDriver\;C:\ProgramData\chocolatey\lib\maven\apache-maven-3.6.3\bin;C:\Program Files\CMake\bin;C:\Program Files\Amazon\AWSCLIV2\;C:\Program Files\Amazon\SessionManagerPlugin\bin\;C:\Program Files\Amazon\AWSSAMCLI\bin\;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;C:\Users\runneradmin\.dotnet\tools;C:\Users\runneradmin\AppData\Local\Microsoft\WindowsApps
  - PYTHONLOCATION: C:\hostedtoolcache\windows\Python\3.8.5\x64
## extensions 
  - osf: 
    - description: DataLad extension for OSF support
    - entrypoints: 
      - datalad_osf.create_sibling_osf.CreateSiblingOSF: 
        - class: CreateSiblingOSF
        - load_error: None
        - module: datalad_osf.create_sibling_osf
        - names: 
          - create-sibling-osf
          - create_sibling_osf
      - datalad_osf.credentials.OSFCredentials: 
        - class: OSFCredentials
        - load_error: None
        - module: datalad_osf.credentials
        - names: 
          - osf-credentials
          - osf_credentials
    - load_error: None
    - module: datalad_osf
    - version: 0.2.0+5.g105c9fd
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - S3
    - WebDAV
    - TorrentParser
    - Feeds
    - Testsuite
  - dependency versions: 
    - aws-0.21.1
    - bloomfilter-2.0.1.0
    - cryptonite-0.25
    - DAV-1.3.4
    - feed-1.2.0.1
    - ghc-8.6.5
    - http-client-0.5.14
    - persistent-sqlite-2.9.3
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.0.1
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - operating system: mingw32 x86_64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - hook
    - external
  - supported repository versions: 
    - 8
  - upgrade supported from repository versions: 
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  - version: 8.20200720.2-g8bfa7990b
## location 
  - path: D:\a\datalad-osf\datalad-osf
  - type: dataset
## metadata_extractors 
  - annex: 
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio: 
    - load_error: No module named 'mutagen' [audio.py:<module>:17]
    - module: datalad.metadata.extractors.audio
  - datacite: 
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core: 
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822: 
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - exif: 
    - load_error: No module named 'exifread' [exif.py:<module>:16]
    - module: datalad.metadata.extractors.exif
  - frictionless_datapackage: 
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image: 
    - load_error: No module named 'PIL' [image.py:<module>:16]
    - module: datalad.metadata.extractors.image
  - xmp: 
    - load_error: No module named 'libxmp' [xmp.py:<module>:20]
    - module: datalad.metadata.extractors.xmp
## python 
  - implementation: CPython
  - version: 3.8.5
## system 
  - distribution: msys_nt-10.0-17763/3.1.6  10/10.0.17763/SP0/Multiprocessor Free
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: cp1252
  - max_path_length: 297
  - name: Windows
  - release: 10
  - type: nt
  - version: 10.0.17763
datalad_osf.tests.test_create_sibling_osf.test_create_osf_existing ... SKIP: TODO
create-sibling-osf(ok): https://osf.io/hvstu/
Versions: annexremote=1.4.3 appdirs=1.4.4 boto=2.49.0 cmd:7z=19.00 cmd:annex=8.20200720.2-g8bfa7990b cmd:bundled-git=UNKNOWN cmd:git=2.28.0.windows.1 cmd:system-git=2.28.0.windows.1 cmd:system-ssh=for humanize=2.6.0 iso8601=0.1.12 keyring=21.3.0 keyrings.alt=3.4.0 msgpack=1.0.0 requests=2.24.0 tqdm=4.48.2 wrapt=1.12.1
Obscure filename: str=b' ;abc' repr=' ;abc'
Encodings: default='utf-8' filesystem='utf-8' locale.prefered='cp1252'
Environment: PATH='C:\\Program Files\\PowerShell\\7;C:\\Users\\runneradmin\\AppData\\Roaming\\Python\\Python38\\Scripts;C:\\hostedtoolcache\\windows\\Python\\3.8.5\\x64\\Scripts;C:\\hostedtoolcache\\windows\\Python\\3.8.5\\x64;C:\\Program Files\\Mercurial\\;C:\\Program Files\\MongoDB\\Server\\4.2\\bin;C:\\ProgramData\\kind;C:\\vcpkg;C:\\cf-cli;C:\\Program Files (x86)\\NSIS\\;C:\\Program Files\\Mercurial\\;C:\\hostedtoolcache\\windows\\stack\\2.3.1\\x64;C:\\ProgramData\\chocolatey\\lib\\ghc.8.10.1\\tools\\ghc-8.10.1\\bin;C:\\Program Files\\dotnet;C:\\mysql-5.7.21-winx64\\bin;C:\\Program Files\\R\\R-4.0.2\\bin\\x64;C:\\Program Files\\Java\\jdk8u265-b01\\bin;C:\\SeleniumWebDrivers\\GeckoDriver;C:\\Program Files (x86)\\sbt\\bin;C:\\Rust\\.cargo\\bin;C:\\Program Files (x86)\\GitHub CLI;C:\\Program Files\\Git\\bin;C:\\hostedtoolcache\\windows\\go\\1.14.6\\x64\\bin;C:\\hostedtoolcache\\windows\\Python\\3.7.8\\x64\\Scripts;C:\\hostedtoolcache\\windows\\Python\\3.7.8\\x64;C:\\hostedtoolcache\\windows\\Ruby\\2.5.8\\x64\\bin;C:\\npm\\prefix;C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI2\\wbin;C:\\windows\\system32;C:\\windows;C:\\windows\\System32\\Wbem;C:\\windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\windows\\System32\\OpenSSH\\;C:\\ProgramData\\Chocolatey\\bin;C:\\Program Files\\Docker;C:\\Program Files\\PowerShell\\7\\;C:\\Program Files\\dotnet\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\110\\DTS\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\120\\DTS\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\130\\DTS\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\140\\DTS\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\150\\DTS\\Binn\\;C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\;C:\\Program Files\\Microsoft Service Fabric\\bin\\Fabric\\Fabric.Code;C:\\Program Files\\Microsoft SDKs\\Service Fabric\\Tools\\ServiceFabricLocalClusterManager;C:\\Program Files\\nodejs\\;C:\\Program Files\\OpenSSL\\bin;C:\\Strawberry\\c\\bin;C:\\Strawberry\\perl\\site\\bin;C:\\Strawberry\\perl\\bin;C:\\Program Files\\Git\\cmd;C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\bin;c:\\tools\\php;C:\\Program Files (x86)\\sbt\\bin;C:\\Program Files (x86)\\Subversion\\bin;C:\\SeleniumWebDrivers\\ChromeDriver\\;C:\\SeleniumWebDrivers\\EdgeDriver\\;C:\\ProgramData\\chocolatey\\lib\\maven\\apache-maven-3.6.3\\bin;C:\\Program Files\\CMake\\bin;C:\\Program Files\\Amazon\\AWSCLIV2\\;C:\\Program Files\\Amazon\\SessionManagerPlugin\\bin\\;C:\\Program Files\\Amazon\\AWSSAMCLI\\bin\\;C:\\Program Files (x86)\\Google\\Cloud SDK\\google-cloud-sdk\\bin;C:\\Users\\runneradmin\\.dotnet\\tools;C:\\Users\\runneradmin\\AppData\\Local\\Microsoft\\WindowsApps' PYTHONLOCATION='C:\\hostedtoolcache\\windows\\Python\\3.8.5\\x64' GIT_CONFIG_PARAMETERS="'init.defaultBranch=dl-test-branch'"
datalad_osf.tests.test_create_sibling_osf.test_create_osf_export ... 

Name                                                 Stmts   Miss  Cover
------------------------------------------------------------------------
datalad_osf\__init__.py                                  8      0   100%
datalad_osf\_version.py                                  4      0   100%
datalad_osf\create_sibling_osf.py                       89     23    74%
datalad_osf\credentials.py                              41     25    39%
datalad_osf\osfclient\__init__.py                        0      0   100%
datalad_osf\osfclient\osfclient\__init__.py              3      0   100%
datalad_osf\osfclient\osfclient\__version__.py           5      0   100%
datalad_osf\osfclient\osfclient\api.py                  32     15    53%
datalad_osf\osfclient\osfclient\exceptions.py            7      1    86%
datalad_osf\osfclient\osfclient\models\__init__.py       6      0   100%
datalad_osf\osfclient\osfclient\models\core.py          46     29    37%
datalad_osf\osfclient\osfclient\models\file.py         115     90    22%
datalad_osf\osfclient\osfclient\models\project.py       33     24    27%
datalad_osf\osfclient\osfclient\models\session.py       34     15    56%
datalad_osf\osfclient\osfclient\models\storage.py       65     47    28%
datalad_osf\osfclient\osfclient\utils.py                41     31    24%
datalad_osf\utils.py                                    50     24    52%
------------------------------------------------------------------------
TOTAL                                                  579    324    44%
----------------------------------------------------------------------
Ran 2 tests in 21465.782s

OK (SKIP=1)
##[error]The operation was canceled.

```

**Comment by adswa** [comment]
the tests run fine on our windows machine

**Comment by mih** [comment]
FTR: This PR patches the osfclient source fork we are carrying. We should be very careful going down this path and make sure there is a corresponding PR in the mother repo, so that we can keep the diff as small as possible.

**Comment by adswa** [comment]
oh yes, that makes sense. I will open a PR at the OSFclient right away.

**Comment by mih** [comment]
I have merged an osfclient update #136 that should make this unnecessary, because it has your upstream patch already.

**Comment by adswa** [comment]
I will drop 96e281c1c046fe86d6f84e19ec1b1cd409f37d4d from this PR (after lunch)

**Comment by adswa** [comment]
Done.

**Pull request merged**
