### PR TITLE
Make better use of OSF capabilties

### LINKED ISSUE #9: Use case: Export an entire dataset and be able to `datalad clone` it again from an OSF URL
This can re-use concepts and code from https://github.com/datalad/git-remote-rclone for the Git part, when putting a repo as an archive on OSstorage. However, alternatively, `osfclient` can be enhanced to see linked storage components (e.g. GitHub repos) to access a repository in its native form. However, the cloud storage access paradigm might make such an approach prohibitively slow.

### LINKED ISSUE #101: Enhance `create-sibling-osf` to use OSF as annex and Git remote
See #100

### PR DESCRIPTION
**Pull request by mih**
This PR enables all kind of things. Here is a demo of the most important aspect

```
(datalad3-dev) mih@meiner /tmp % datalad create mytest
[INFO   ] Creating a new annex repo at /tmp/mytest 
[INFO   ] Scanning for unlocked files (this may take some time) 
create(ok): /tmp/mytest (dataset)

(datalad3-dev) mih@meiner /tmp % cd mytest
(datalad3-dev) mih@meiner /tmp/mytest (git)-[master] % echo 123 > dummy
(datalad3-dev) mih@meiner /tmp/mytest (git)-[master] % datalad save
add(ok): /tmp/mytest/dummy (file)
save(ok): /tmp/mytest (dataset)
action summary:
  add (ok: 1)
  save (ok: 1)

(datalad3-dev) mih@meiner /tmp/mytest (git)-[master] % datalad create-sibling-osf
create-sibling-osf(ok): https://osf.io/yjmwb/
[INFO   ] Configure additional publication dependency on "osf-storage" 
configure-sibling(ok): /tmp/mytest (sibling)
(datalad3-dev) mih@meiner /tmp/mytest (git)-[master] % datalad push --to osf
copy(ok): /tmp/mytest/dummy (file) [to osf-storage...]                                       
publish(ok): /tmp/mytest (dataset) [refs/heads/master->osf:refs/heads/master [new branch]]   
publish(ok): /tmp/mytest (dataset) [refs/heads/git-annex->osf:refs/heads/git-annex [new branch]]                                                                                          
```

image

and importantly enables this

```
(datalad3-dev) mih@meiner /tmp % datalad clone osf://yjmwb mytest_clone
[INFO   ] Scanning for unlocked files (this may take some time)                              
install(ok): /tmp/mytest_clone (dataset)

(datalad3-dev) mih@meiner /tmp % cd mytest_clone
(datalad3-dev) mih@meiner /tmp/mytest_clone (git)-[master] % datalad get dummy
get(ok): /tmp/mytest_clone/dummy (file) [from osf-storage...]
(datalad3-dev) mih@meiner /tmp/mytest_clone (git)-[master] % cat dummy
123
```

None of this here is polished or optimized, but it works in principle!

- Replaces #100 
- Fixes #101 
- Fixes #9 
- Enable OSF category specification (use 'data' by default)
- Enable tag specification (use 'DataLad dataset' and dataset `id` for all datasets)
- Create public OSF project siblings

I would very much appreciate help writing tests for this new functionality and also for adjusting the docs.

### CODE REVIEW

**Comment by mih** [comment]
Both targile and zipfile in the stdlub support lzma compression. Use them instead of an external dependecy on 7z.

**Comment by mih** [comment]
So it seems that the code has some kind of line-ending issues (oh how I love windows).

In the logs I see:
```
[DEBUG] Non-progress stderr: b'fatal: This version of fast-import does not support feature done\r'
[```

Somehow a carriage return makes it into the stream that fast-export sends to fast-import(?). I failed to discover how and why.

**Comment by sappelhoff** [comment]
Can we get this feature for linux/osx anyhow? :-) or is it a strong blocker if windows tests are not passing?

**Comment by mih** [comment]
OK, so the remaining test failures are not unique to this PR.

**Comment by adswa** [comment]
FTR: I will overhaul the documentation today

**Comment by sappelhoff** [comment]
Let me know if you need/could use help @adswa

**Comment by adswa** [comment]
thx much @sappelhoff, I'm still typing, but will create a PR later and appreciate feedback and ideas & commits with improvements

**Pull request merged**
