### PR TITLE
Replace git-remote-osf implementation with `datalad-annex::` from `datalad-next`

### LINKED ISSUE #112: No windows support for git-remote-osf
I have no idea why it isn't working, but it is not. The starting point for forensics is https://github.com/datalad/datalad-osf/pull/106#issuecomment-653772696

I would very much appreciate if a person familiar with Git on Windows could have a look.

### LINKED ISSUE #142: Error handling in git-remote
Error handling by git-remote isn't particularly nice yet. If there's an exception, python's standard way of printing it including traceback applies, then git realizes that call went wrong and ultimately datalad prints an error result.

Invalid project URL:
```
❱ datalad clone osf://2ynvg/sdf/sfd
[ERROR  ] Failed to clone from any candidate source URL. Encountered errors per each url were:                                                                                                                                                                                                       
| - osf://2ynvg/sdf/sfd
  CommandError: 'git clone --progress osf://2ynvg/sdf/sfd /tmp/sfd' failed with exitcode 128 [err: 'Cloning into '/tmp/sfd'...
fatal: bad revision 'HEAD'
Traceback (most recent call last):
  File "/home/ben/venvs/datalad-osf-dev/bin/git-remote-osf", line 33, in <module>
    sys.exit(load_entry_point('datalad-osf', 'console_scripts', 'git-remote-osf')())
  File "/home/ben/work/hacking/datalad-osf/datalad_osf/git_remote.py", line 484, in main
    osf = OSFGitRemote(gitdir, remote, url)
  File "/home/ben/work/hacking/datalad-osf/datalad_osf/git_remote.py", line 60, in __init__
    raise RuntimeError("Only URLs of type osf://<PROJECT ID> are "
RuntimeError: Only URLs of type osf://<PROJECT ID> are supported. Got: osf://2ynvg/sdf/sfd'] [install(/tmp/sfd)] 
install(error): /tmp/sfd (dataset) [Failed to clone from any candidate source URL. Encountered errors per each url were:
- osf://2ynvg/sdf/sfd
  CommandError: 'git clone --progress osf://2ynvg/sdf/sfd /tmp/sfd' failed with exitcode 128 [err: 'Cloning into '/tmp/sfd'...
fatal: bad revision 'HEAD'
Traceback (most recent call last):
  File "/home/ben/venvs/datalad-osf-dev/bin/git-remote-osf", line 33, in <module>
    sys.exit(load_entry_point('datalad-osf', 'console_scripts', 'git-remote-osf')())
  File "/home/ben/work/hacking/datalad-osf/datalad_osf/git_remote.py", line 484, in main
    osf = OSFGitRemote(gitdir, remote, url)
  File "/home/ben/work/hacking/datalad-osf/datalad_osf/git_remote.py", line 60, in __init__
    raise RuntimeError("Only URLs of type osf://<PROJECT ID> are "
RuntimeError: Only URLs of type osf://<PROJECT ID> are supported. Got: osf://2ynvg/sdf/sfd']]
```

This is not easy to parse for users and looks way more frightening than necessary.

Initially thought to simply put the call to `main()` in a `try ... except` in order to just print the message and exit non-zero. For some reason that isn't obvious to me yet, this doesn't work. The error used for illustration above would not end up in that `except Exception`.
However, for most errors we should probably use the remote helper protocol anyways (not that this doesn't work by design of our git-remote for any exception happening before `osf.communicate()`.

Talking of error handling: We should look into the `fatal: bad revision 'HEAD'`, too. As far as I can tell this is reported for each and every clone attempt. Smells like an improper implementation of git's remote helper protocol.

### LINKED ISSUE #148: datalad second push to osf fails because of differing git commit ids
**Describe the bug**
After creating an OSF sibling, the first `datalad push --to osf` succeeds, but the second one fails with `[rejected] (fetch first)]`. Inspecting the git repositories shows that the commit IDs are different in the OSF remote.

**To Reproduce**

```shell
$ datalad create example-osf
[INFO   ] Creating a new annex repo at /home/pflueger/work/dl-test/example-osf 
[INFO   ] Scanning for unlocked files (this may take some time) 
create(ok): /home/pflueger/work/dl-test/example-osf (dataset)

$ cd example-osf/

$ wget http://www.tldp.org/LDP/Bash-Beginners-Guide/Bash-Beginners-Guide.pdf
[…]

$ datalad save -m 'a pdf'
add(ok): Bash-Beginners-Guide.pdf (file)                                                                                
save(ok): . (dataset)                                                                                                   
action summary:                                                                                                         
  add (ok: 1)
  save (ok: 1)

$ vim README.md

$ git add README.md

$ git commit -m 'thing'
[master e6db074] thing
 1 file changed, 2 insertions(+)
 create mode 100644 README.md

$ datalad create-sibling-osf --title example-osf
create-sibling-osf(ok): https://osf.io/hf624/
[INFO   ] Configure additional publication dependency on "osf-storage" 
configure-sibling(ok): . (sibling)

$ datalad push --to osf
copy(ok): Bash-Beginners-Guide.pdf (file) [to osf-storage...]                                                           
publish(ok): . (dataset) [refs/heads/master->osf:refs/heads/master [new branch]]                                        
publish(ok): . (dataset) [refs/heads/git-annex->osf:refs/heads/git-annex [new branch]]          
                        
$ datalad push --to osf
[ERROR  ] refs/heads/master->osf:refs/heads/master [rejected] (fetch first) [publish(/home/pflueger/work/dl-test/example-osf)]                                                                                                                  
publish(error): . (dataset) [refs/heads/master->osf:refs/heads/master [rejected] (fetch first)]                         
                                                                                                                       Potential hints to solve encountered errors:                                                                             
1: Updates were rejected because the remote contains work that you do not have locally. This is usually caused by another repository pushing to the same ref. You may want to first integrate the remote changes (e.g., 'git pull ...') before pushing again. See the 'Note about fast-forwards' in 'git push --help' for details.

$ git log master
commit e6db074a5c196839be747a178739523bc00ab5c2 (HEAD -> master, osf/master, refs/osf/osf/master)
Author: Mika Pflüger <mika.pflueger@pik-potsdam.de>
Date:   Fri May 7 17:25:58 2021 +0200

    thing

commit 7cf3bc9bb4f86fb33f08b7f7a3d259a6ffe190eb
Author: Mika Pflüger <mika.pflueger@pik-potsdam.de>
Date:   Fri May 7 17:25:29 2021 +0200

    a pdf

commit 4909c54ee3c4288791e1fdf70ad0ef98f54c14ee
Author: Mika Pflüger <mika.pflueger@pik-potsdam.de>
Date:   Fri May 7 17:25:16 2021 +0200

    [DATALAD] new dataset


$ # compare with what we get in a fresh clone of the git repo
$ cd ..
$ git clone osf://hf624
Cloning into 'hf624'...
100%|█████████████████| 145/145 [00:00<00:00, 934kbytes/s]
Downloading repository archive
100%|█████████████████| 18.6k/18.6k [00:00<00:00, 5.51Mbytes/s]
Extracting repository archive

$ cd hf624/
Bash-Beginners-Guide.pdf@  README.md

$ git log
commit f6e3ce21a7d6a5f0d8d820a4f40873c9370a68ba (HEAD -> master, origin/master, origin/HEAD, refs/osf/origin/master)
Author: Mika Pflüger <mika.pflueger@pik-potsdam.de>
Date:   Fri May 7 17:25:58 2021 +0200

    thing

commit ba3846a3968517b4017b33f6a1f5ff573cbddbee
Author: Mika Pflüger <mika.pflueger@pik-potsdam.de>
Date:   Fri May 7 17:25:29 2021 +0200

    a pdf

commit 2246d22cc3758b612f75862e35ca304e4956cedb
Author: Mika Pflüger <mika.pflueger@pik-potsdam.de>
Date:   Fri May 7 17:25:16 2021 +0200

    [DATALAD] new dataset

```

As you can see, the ID of the first commit is `4909c54ee3c` in the original datalad repo, and `2246d22cc375` in the clone obtained from OSF.

**Desktop (please complete the following information):**
 - OS: Ubuntu 21-04
<details>
<summary>Datalad WTF</summary>

```

# WTF
## configuration <SENSITIVE, report disabled by configuration>
## credentials 
  - keyring: 
    - active_backends: 
      - SecretService Keyring
      - kwallet DBusKeyring
      - EncryptedKeyring with [PBKDF2] AES256.CFB v.1.0 at /home/pflueger/.local/share/python_keyring/crypted_pass.cfg
      - PlaintextKeyring with no encyption v.1.0 at /home/pflueger/.local/share/python_keyring/keyring_pass.cfg
    - config_file: /home/pflueger/.config/python_keyring/keyringrc.cfg
    - data_root: /home/pflueger/.local/share/python_keyring
## datalad 
  - full_version: 0.14.3
  - version: 0.14.3
## dataset 
  - id: 9f60be2e-3205-43be-9f1b-acecc95a1649
  - metadata: <SENSITIVE, report disabled by configuration>
  - path: /tmp/hf624
  - repo: AnnexRepo
## dependencies 
  - annexremote: 1.4.3
  - appdirs: 1.4.4
  - boto: 2.49.0
  - cmd:7z: 16.02
  - cmd:annex: 8.20210223-1~ndall+1
  - cmd:bundled-git: 2.24.0
  - cmd:git: 2.24.0
  - cmd:system-git: 2.30.2
  - cmd:system-ssh: 8.4p1
  - exifread: 2.3.2
  - git: 3.1.12
  - gitdb: 4.0.5
  - humanize: 0.0.0
  - iso8601: 0.1.13
  - keyring: 22.2.0
  - keyrings.alt: 4.0.2
  - msgpack: 1.0.0
  - mutagen: 1.45.1
  - requests: 2.25.1
  - wrapt: 1.12.1
## environment 
  - LANG: en_US.UTF-8
  - LANGUAGE: en_US:
  - LC_ADDRESS: de_DE.UTF-8
  - LC_IDENTIFICATION: de_DE.UTF-8
  - LC_MEASUREMENT: de_DE.UTF-8
  - LC_MONETARY: de_DE.UTF-8
  - LC_NAME: de_DE.UTF-8
  - LC_NUMERIC: de_DE.UTF-8
  - LC_PAPER: de_DE.UTF-8
  - LC_TELEPHONE: de_DE.UTF-8
  - LC_TIME: de_DE.UTF-8
  - PATH: /home/pflueger/.pyenv/shims:/home/pflueger/.local/conda/condabin:/home/pflueger/.local/bin:/home/pflueger/go/bin:/home/pflueger/.pyenv/bin:/home/pflueger/.poetry/bin:/home/pflueger/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
## extensions 
  - osf: 
    - description: DataLad extension for OSF support
    - entrypoints: 
      - datalad_osf.create_sibling_osf.CreateSiblingOSF: 
        - class: CreateSiblingOSF
        - load_error: None
        - module: datalad_osf.create_sibling_osf
        - names: 
          - create-sibling-osf
          - create_sibling_osf
      - datalad_osf.credentials.OSFCredentials: 
        - class: OSFCredentials
        - load_error: None
        - module: datalad_osf.credentials
        - names: 
          - osf-credentials
          - osf_credentials
    - load_error: None
    - module: datalad_osf
    - version: 0.2.3.1
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Feeds
    - Testsuite
    - S3
    - WebDAV
  - dependency versions: 
    - aws-0.20
    - bloomfilter-2.0.1.0
    - cryptonite-0.25
    - DAV-1.3.3
    - feed-1.0.0.0
    - ghc-8.4.4
    - http-client-0.5.13.1
    - persistent-sqlite-2.8.2
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.0
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - operating system: linux x86_64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - httpalso
    - borg
    - hook
    - external
  - supported repository versions: 
    - 8
  - upgrade supported from repository versions: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  - version: 8.20210223-1~ndall+1
## location 
  - path: /tmp/hf624
  - type: dataset
## metadata_extractors 
  - annex (datalad 0.14.3): 
    - distribution: datalad 0.14.3
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio (datalad 0.14.3): 
    - distribution: datalad 0.14.3
    - load_error: None
    - module: datalad.metadata.extractors.audio
    - version: None
  - datacite (datalad 0.14.3): 
    - distribution: datalad 0.14.3
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core (datalad 0.14.3): 
    - distribution: datalad 0.14.3
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822 (datalad 0.14.3): 
    - distribution: datalad 0.14.3
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - exif (datalad 0.14.3): 
    - distribution: datalad 0.14.3
    - load_error: None
    - module: datalad.metadata.extractors.exif
    - version: None
  - frictionless_datapackage (datalad 0.14.3): 
    - distribution: datalad 0.14.3
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image (datalad 0.14.3): 
    - distribution: datalad 0.14.3
    - load_error: None
    - module: datalad.metadata.extractors.image
    - version: None
  - xmp (datalad 0.14.3): 
    - distribution: datalad 0.14.3
    - load_error: No module named 'libxmp' [xmp.py:<module>:20]
    - module: datalad.metadata.extractors.xmp
## metadata_indexers 
## python 
  - implementation: CPython
  - version: 3.9.4
## system 
  - distribution: ubuntu/21.04/hirsute
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 266
  - name: Linux
  - release: 5.11.0-16-generic
  - type: posix
  - version: #17-Ubuntu SMP Wed Apr 14 20:12:43 UTC 2021

```

</details>

**Expected behavior**
I expect that following the [tutorial](http://docs.datalad.org/projects/osf/en/latest/tutorial.html), I get a datalad repo with an OSF sibling which can be pushed multiple times.

**Additional Info**

I haven't looked into datalad-osf code myself yet, but I think that the inconsistency comes straight from git-remote-osf.

### LINKED ISSUE #162: Support push with -f
I did some squashing, and I'd like to push to OSF. Since the commit history is ammended, I need to force push, but the extension doesnt suppost `datalad push --to osf -f gitpush`

```(dl-osf) asmacdo@typhon:~/datasets/opfvta-replication-2023$ datalad push --to osf -f  gitpush
Update availability for 'osf':  75%|████████████████████████████████▎          | 3.00/4.00 [00:00<00:00, 8.38k Steps/s]CommandError: 'git -c diff.ignoreSubmodules=none push --progress --porcelain --force osf master:master git-annex:git-annex' failed with exitcode 1 under /home/asmacdo/datasets/opfvta-replication-2023
[WARNING] Failed to query keyring: InitError(Failed to create the collection: Prompt dismissed..) 
[WARNING] Failed to query keyring: InitError(Failed to create the collection: Prompt dismissed..) 
[WARNING] Failed to query keyring: InitError(Failed to create the collection: Prompt dismissed..) 
100%|██████████| 145/145 [00:00<00:00, 999kbytes/s]
warning: helper osf does not support 'force'
warning: Not updating refs/heads/master (new tip e99e5e72c462520b904a4c2037d2a9c0ebafe411 does not contain 474a1c5caf97415c5dd384deb6b3ffce8799974c)
fatal: Command '['git', 'fast-import', '--quiet', '--import-marks=/home/asmacdo/datasets/opfvta-replication-2023/.git/osf/osf/osf.marks', '--export-marks=/home/asmacdo/datasets/opfvta-replication-2023/.git/osf/osf/osf.marks']' returned non-zero exit status 1.
error: failed to push some refs to 'osf://dbxpt'
```

### LINKED ISSUE #174: Make datalad-annex:: compatible with datalad-osf
The `git-remote-osf` helper of https://github.com/datalad/datalad-osf is the director predecessor of `datalad-annex::`. It suffers from a number of limitations that have since been improved in `datalad-annex::`. Therefore it would be nice to be able to use the latter instead of the former without loosing data access.

There are two issues. One is

- https://github.com/datalad/datalad-next/issues/410

The other is that `datalad-annex::` used the `XDLRA` annex backend to deposit repositories, while the `datalad-osf` special remote hard-codes the target files for such keys. The content is, however, exactly identical.

One solution would be to transparently map between the hard-coded locations and the respective `XDLRA` keys. Possible like this:

```diff
diff --git a/datalad_osf/annex_remote.py b/datalad_osf/annex_remote.py
index c264f64..55dc45f 100755
--- a/datalad_osf/annex_remote.py
+++ b/datalad_osf/annex_remote.py
@@ -253,6 +253,13 @@ class OSFSpecialRemote(ExportRemote):
                 f.path.lstrip(posixpath.sep): f
                 for f in self.storage.files
             }
+            for p, key in (
+                ('.git/refs', 'XDLRA--refs'),
+                ('.git/repo.zip', 'XDLRA--repo-export'),
+            ):
+                handle = self._files.get(p)
+                if handle is not None:
+                    self._files[key] = handle
         return self._files
 
     def removeexportdirectory(self, remote_directory):
```

Some additional though needs to go into transitions. I see two scenarios:

- Keep the hard-coded names and map to `XDLRA` key names on read and on write. There would be no change to the layout on OSF (good). But the first write via `datalad-annex::` would make the deposit incompatible with `git-remote-osf` (relevant for existing clones). So this would also need an update
- Transition to XDLRA by mapping on read, but not on write. This would make things more uniform across special remotes and expectations, but would require `datalad-osf` users to transition to `datalad-annex::` explicitly, or also require an update to `git-remote-osf`.

I am leaning towards the first solution. This would be the approach:

- implement two-way mapping to keep the OSF project content identical wrt file names, and enable direct use of `git-annex-remote-osf` with `datalad-annex::` (assuming https://github.com/datalad/datalad-next/issues/410 is implemented)
- replace `git-remote-osf` to become a thing wrapper around `datalad-annex::`

OSF users would be required to upgrade `datalad-osf` whenever the update an OSF deposit via `datalad-annex::` or via an upgraded `git-remote-osf`. The latter would be OK, given the software upgrade has already happened. The former requires an intentional change on the user end -- OK too IMHO.

### PR DESCRIPTION
**Pull request by mih**
Massive code-removal (25% of the entire codebase). The entire git-remote helper became obsolete and is more-or-less entirely removed.

- Requires https://github.com/datalad/datalad-next/pull/411
- Closes #174 
- Closes #162
- Closes #148 
- Closes #142 
- Closes #112

### CODE REVIEW

**Comment by adswa** [comment]
I gave this a few real-life tests, and it works nicely! The doc CIs are all unhappy, though, I'll investigate

**Comment by adswa** [comment]
I just realized that with this change, exports can be cloned, too. That's pretty cool. I will push a documentation change to reflect this.

**Comment by adswa** [comment]
oh, and we can push with datalad commands even to pure storage remotes! :rocket:

**Comment by mih** [comment]
Wonderful addition! Thx @adswa

**Comment by mih** [comment]
datalad-next 1.0.0b3 is out, it has all we need in a release now.

**Comment by mih** [comment]
Tests pass with datalad-next 1.0.0b3!

**Pull request merged**
